In [1]:
import torch
print(torch. __version__)

2.9.1+cpu


## Scaler

In [ ]:
scaler=torch.tensor(45)
scaler.ndim  # number of dimensions 
scaler.shape # number of elements
print(scaler)


tensor(45)


## Vector

In [8]:
vector=torch.tensor([34,45,4])
vector.ndim  # number of dimensions 
vector.shape # number of elements
print(vector)

tensor([34, 45,  4])


# MATRIX

In [23]:
matrix=torch.tensor([[3,4],[6,7],[2,1]])
print(matrix.ndim)
print(type(matrix))
print(matrix)
print(matrix[0]) 
print(matrix[1])
print(matrix.shape) # 3 x 2 matrix

2
<class 'torch.Tensor'>
tensor([[3, 4],
        [6, 7],
        [2, 1]])
tensor([3, 4])
tensor([6, 7])
torch.Size([3, 2])


# Tensor

In [ ]:
tensor_ex=torch.tensor([[[1,2,3],[4,3,5],[3,5,6]]])
print(tensor_ex)

3
torch.Size([1, 3, 3])
tensor([[[1, 2, 3],
         [4, 3, 5],
         [3, 5, 6]]])


In [22]:
tensor_ex.ndim

3

In [24]:
tensor_ex.shape

torch.Size([1, 3, 3])