In [1]:
import torch
print(torch. __version__)

2.10.0+cu128


In [9]:
!nvidia-smi

Tue Mar 31 17:08:01 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   40C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

## Scaler

In [2]:
scaler=torch.tensor(45)
scaler.ndim  # number of dimensions 
scaler.shape # number of elements
print(scaler)


tensor(45)


## Vector

In [3]:
vector=torch.tensor([34,45,4])
vector.ndim  # number of dimensions 
vector.shape # number of elements
print(vector)

tensor([34, 45,  4])


# MATRIX

In [4]:
matrix=torch.tensor([[3,4],[6,7],[2,1]])
print(matrix.ndim)
print(type(matrix))
print(matrix)
print(matrix[0]) 
print(matrix[1])
print(matrix.shape) # 3 x 2 matrix

2
<class 'torch.Tensor'>
tensor([[3, 4],
        [6, 7],
        [2, 1]])
tensor([3, 4])
tensor([6, 7])
torch.Size([3, 2])


# Tensor

In [5]:
tensor_ex=torch.tensor([[[1,2,3],[4,3,5],[3,5,6]]])
print(tensor_ex)

tensor([[[1, 2, 3],
         [4, 3, 5],
         [3, 5, 6]]])


In [6]:
tensor_ex.ndim

3

In [7]:
tensor_ex.shape

torch.Size([1, 3, 3])